import forms from '@tailwindcss/forms'
import type { Config } from 'tailwindcss'

export default {
  darkMode: 'class',
  content: ['./index.html', './src/**/*.{ts,tsx}'],
  theme: {
    extend: {
      colors: {
        'on-primary-fixed': '#001a42',
        'on-surface-variant': '#c2c6d6',
        surface: '#101415',
        'primary-fixed': '#d8e2ff',
        'on-secondary-fixed-variant': '#004883',
        'on-tertiary-fixed': '#001e2f',
        'surface-container-lowest': '#0b0f10',
        'surface-container-high': '#272a2c',
        'surface-bright': '#363a3b',
        'error-container': '#93000a',
        'secondary-container': '#0267b8',
        'on-primary-fixed-variant': '#004395',
        'on-surface': '#e0e3e5',
        'tertiary-container': '#009ada',
        'inverse-on-surface': '#2d3133',
        'tertiary-fixed-dim': '#89ceff',
        background: '#101415',
        'secondary-fixed-dim': '#a4c9ff',
        'on-primary': '#002e6a',
        'inverse-surface': '#e0e3e5',
        'primary-container': '#4d8eff',
        'secondary-fixed': '#d4e3ff',
        error: '#ffb4ab',
        'on-secondary-container': '#d6e5ff',
        'on-tertiary-fixed-variant': '#004c6e',
        secondary: '#a4c9ff',
        'outline-variant': '#424754',
        'surface-container': '#1d2022',
        tertiary: '#89ceff',
        'on-tertiary-container': '#002d43',
        'surface-container-low': '#191c1e',
        'on-tertiary': '#00344d',
        'on-secondary-fixed': '#001c39',
        'on-error': '#690005',
        'tertiary-fixed': '#c9e6ff',
        'on-background': '#e0e3e5',
        'surface-dim': '#101415',
        'surface-container-highest': '#323537',
        'surface-tint': '#adc6ff',
        'inverse-primary': '#005ac2',
        'surface-variant': '#323537',
        'on-primary-container': '#00285d',
        primary: '#adc6ff',
        outline: '#8c909f',
        'on-secondary': '#00315d',
        'on-error-container': '#ffdad6',
        'primary-fixed-dim': '#adc6ff',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px',
      },
      spacing: {
        'container-max': '1280px',
        lg: '40px',
        gutter: '24px',
        md: '24px',
        base: '4px',
        xl: '64px',
        sm: '16px',
        xs: '8px',
      },
      fontFamily: {
        'label-sm': ['Geist'],
        'code-md': ['JetBrains Mono'],
        'body-md': ['Inter'],
        'headline-md': ['Geist'],
        'body-lg': ['Inter'],
        display: ['Geist'],
        'headline-lg': ['Geist'],
      },
      fontSize: {
        'label-sm': ['12px', { lineHeight: '1', letterSpacing: '0.05em', fontWeight: '500' }],
        'code-md': ['14px', { lineHeight: '1.7', fontWeight: '400' }],
        'body-md': ['16px', { lineHeight: '1.6', fontWeight: '400' }],
        'headline-md': ['24px', { lineHeight: '1.3', fontWeight: '600' }],
        'body-lg': ['18px', { lineHeight: '1.6', fontWeight: '400' }],
        display: ['48px', { lineHeight: '1.1', letterSpacing: '-0.02em', fontWeight: '700' }],
        'headline-lg': ['32px', { lineHeight: '1.2', fontWeight: '600' }],
      },
    },
  },
  plugins: [forms],
} satisfies Config
